%% Start of file `resume.cls'.
% Resume Class File
%
% Author:
% Robert Hameetman <rob@rham.io>
% http://rham.io
%
% Notes:
%    This class file defines the structure and layout of the resume tex file (resume.tex).
%
% Class license:
% LPPL v1.3c (http://www.latex-project.org/lppl)
%


%-------------------------------------------------------------------------------
%                Identification
%-------------------------------------------------------------------------------
\NeedsTeXFormat{LaTeX2e}[195/12/01]
\ProvidesClass{resume}[2017/11/13 v1.0.0 Resume Class - Robert Hameetman]


%-------------------------------------------------------------------------------
%                Class options
%-------------------------------------------------------------------------------